name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#     - name: clang-tidy review
#       uses: ZedThree/clang-tidy-review@v0.7.0

#       id: review

#       # If there are any comments, fail the check
#     - name: Passed C++ style guide checks  
#       #if: steps.review.outputs.total_comments > 0
#       #run: exit 1
#       run: |
#         number=${{steps.review.outputs.total_comments}}
#         echo "num_comments = ${{steps.review.outputs.total_comments}}"
#         echo "number = ${number}"
#         if [ ${number} == 0 ]; then
#           echo "test"
#           exit 1
#         fi  
    - name: Check C++ changes against style guide
      uses: ZedThree/clang-tidy-review@v0.7.0
      id: id_review
      with:
        # PLACEMARKER: list of clang-tidy checks
        clang_tidy_checks: '-*,performance-*,readability-*,bugprone-*,clang-analyzer-*,cppcoreguidelines-*,mpi-*,misc-*,-readability-implicit-bool-conversion,-readability-qualified-auto,-cppcoreguidelines-owning-memory,-cppcoreguidelines-avoid-magic-numbers,-readability-magic-numbers,-readability-static-accessed-through-instance,-cppcoreguidelines-pro-type-static-cast-downcast,-bugprone-suspicious-enum-usage,-readability-uppercase-literal-suffix,-cppcoreguidelines-avoid-non-const-global-variables,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-misc-no-recursion,-readability-isolate-declaration,-cppcoreguidelines-pro-type-vararg,-misc-non-private-member-variables-in-classes,-performance-no-automatic-move,-readability-avoid-const-params-in-decls,-cppcoreguidelines-non-private-member-variables-in-classes'
        
    - name: Passed C++ style guide checks
      if: steps.static_analysis.outputs.total_comments > 0
      run: exit 1
