name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: clang-tidy review
      uses: ZedThree/clang-tidy-review@v0.7.0

      id: review

      # If there are any comments, fail the check
    - name: Passed C++ style guide checks  
      #if: steps.review.outputs.total_comments > 0
      #run: exit 1
      run: |
        number=${{steps.review.outputs.total_comments}}
        echo "num_comments = ${{steps.review.outputs.total_comments}}"
        echo "number = ${number}"
        if [ ${number} > 0 ]; then
          echo "test"
          exit 1
        fi  
